<?php

$title = 'Tambah Prajurit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('prajurit', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '<br>';
echo $this->formRow($form->get('nama'));
echo '<br>';
echo $this->formRow($form->get('pangkat'));
echo '<br>';
echo $this->formRow($form->get('inmission'));
echo '<br>';
echo $this->formSubmit($form->get('submit'));
echo '<br>';
echo $this->form()->closeTag();
